### ISSUE TITLE
what is the authentication for ifunny?

### ISSUE THREAD

**Issue by reteps** [bakapear/ifunny-api#1]

**Comment by bakapear** [comment]
We're working on making a generatable auth token.

**Comment by reteps** [comment]
great! thanks bro

**Comment by Chewsterchew** [comment]
I guess closing means it's been implemented?

**Comment by bash163** [comment]
@Chewsterchew it probably won't be available for quite some time. Please contact me on Discord: bash#0001 and I will give one to you.
